tap "1password/tap"
tap "achannarasappa/tap"
tap "adoptopenjdk/openjdk"
tap "artginzburg/tap"
tap "blacktop/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "humanlogio/tap"
tap "jakehilborn/jakehilborn"
tap "jandedobbeleer/oh-my-posh"
tap "mas-cli/tap"
tap "microsoft/git"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
tap "robotsandpencils/made"
tap "tarkah/tickrs"
tap "wix/brew"
tap "xcodesorg/made"
brew "aria2"
brew "atuin"
brew "libusb"
brew "libusb-compat"
brew "bat"
brew "btop"
brew "cheat"
brew "chezmoi"
brew "gnutls"
brew "qemu"
brew "colima"
brew "deno"
brew "dialog"
brew "difftastic"
brew "docutils"
brew "drill"
brew "dust"
brew "folly"
brew "ext4fuse"
brew "eza"
brew "fd"
brew "sdl2"
brew "firebase-cli"
brew "gawk"
brew "gh"
brew "git"
brew "gnupg"
brew "smartmontools"
brew "gsmartcontrol"
brew "htop"
brew "httpie"
brew "ios-deploy"
brew "iperf"
brew "jless"
brew "jq"
brew "micro"
brew "miller"
brew "mise"
brew "mosh"
brew "mtr"
brew "ncdu"
brew "nushell"
brew "p7zip"
brew "pandoc"
brew "pgcli"
brew "tcl-tk"
brew "python-tk@3.11"
brew "python@3.10"
brew "rclone"
brew "sampler"
brew "sd"
brew "semgrep"
brew "sevenzip"
brew "swiftlint"
brew "tailscale"
brew "telnet"
brew "tldr"
brew "ugit"
brew "ugrep"
brew "vercel-cli"
brew "virt-manager"
brew "wakeonlan"
brew "watchman"
brew "webhook"
brew "xcodes"
brew "yq"
brew "yt-dlp"
brew "zellij"
brew "zinit"
brew "zoxide"
brew "zsh"
brew "achannarasappa/tap/ticker"
brew "artginzburg/tap/sudo-touchid"
brew "blacktop/tap/ipsw"
brew "humanlogio/tap/humanlog"
brew "jakehilborn/jakehilborn/displayplacer"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "mas-cli/tap/mas"
brew "qmk/qmk/qmk"
brew "tarkah/tickrs/tickrs"
brew "wix/brew/applesimutils"
cask "1password"
cask "1password-cli"
cask "android-studio"
cask "apparency"
cask "autodesk-fusion360"
cask "balenaetcher"
cask "blackhole-2ch"
cask "blender"
cask "calibre"
cask "cheatsheet"
cask "cyberduck"
cask "detox-instruments"
cask "discord"
cask "docker"
cask "dotnet-sdk-preview"
cask "duckduckgo"
cask "firefox-developer-edition"
cask "flipper"
cask "font-cascadia-code-pl"
cask "font-caskaydia-cove-nerd-font"
cask "gb-studio"
cask "github"
cask "godot"
cask "google-chrome"
cask "hiddenbar"
cask "insomnia"
cask "isimulator"
cask "itch"
cask "iterm2"
cask "macfuse"
cask "mdimagesizemdimporter"
cask "messenger"
cask "moonlight"
cask "motrix"
cask "notion"
cask "obsidian"
cask "openrgb"
cask "pieces"
cask "pieces-os"
cask "qflipper"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlvideo"
cask "qmk-toolbox"
cask "raycast"
cask "react-native-debugger"
cask "readdle-spark"
cask "rockboxutility"
cask "sdformatter"
cask "session-manager-plugin"
cask "sf-symbols"
cask "shottr"
cask "sidequest"
cask "signal"
cask "sim-genie"
cask "spacedrive"
cask "steam"
cask "syncthing"
cask "syntax-highlight"
cask "telegram"
cask "thunderbird"
cask "ticktick"
cask "utm"
cask "via"
cask "vial"
cask "visual-studio-code"
cask "vlc"
cask "vox"
cask "wireshark"
cask "xcodes"
cask "xscope"
cask "yubico-yubikey-manager"
cask "zoom"
cask "zulu11"
mas "1Blocker", id: 1365531024
mas "1Password for Safari", id: 1569813296
mas "Actions", id: 1586435171
mas "AdGuard Home", id: 1543143740
mas "Bakery", id: 1575220747
mas "Bear", id: 1091189122
mas "CardPointers", id: 1472875808
mas "Color Picker", id: 1545870783
mas "Cozy Grove", id: 1466130749
mas "Craft", id: 1487937127
mas "Dark Noise", id: 1465439395
mas "Dark Reader for Safari", id: 1438243180
mas "Darkroom", id: 953286746
mas "Deliveries", id: 290986013
mas "Developer", id: 640199958
mas "Dropover", id: 1355679052
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "GoodLinks", id: 1474335294
mas "Goodnotes", id: 1444383602
mas "HACK", id: 1464477788
mas "Home Assistant", id: 1099568401
mas "Hush", id: 1544743900
mas "iMovie", id: 408981434
mas "Infuse", id: 1136220934
mas "Ivory", id: 6444602274
mas "Jayson", id: 1468691718
mas "Keepa - Price Tracker", id: 1533805339
mas "Keynote", id: 409183694
mas "Mela", id: 1568924476
mas "Microsoft Remote Desktop", id: 1295203466
mas "Noir", id: 1592917505
mas "Notability", id: 360593530
mas "Numbers", id: 409203825
mas "Okta Extension App", id: 1439967473
mas "One Thing", id: 1604176982
mas "Pages", id: 409201541
mas "Pandan", id: 1569600264
mas "Pasteboard Viewer", id: 1499215709
mas "Pastel", id: 413897608
mas "Pi-hole Remote", id: 1515445551
mas "PiPifier", id: 1160374471
mas "Pixelmator Pro", id: 1289583905
mas "Plash", id: 1494023538
mas "Playgrounds", id: 1496833156
mas "Poolsuite FM", id: 1514817810
mas "Rakuten Cash Back", id: 1451893560
mas "Reeder", id: 1529448980
mas "Refined GitHub", id: 1519867270
mas "Save to Matter", id: 1548677272
mas "Slack", id: 803453959
mas "Steam Link", id: 1246969117
mas "Streaks", id: 963034692
mas "Structured", id: 1499198946
mas "Tailscale", id: 1475387142
mas "TestFlight", id: 899247664
mas "The Unarchiver", id: 425424353
mas "Transporter", id: 1450874784
mas "Userscripts-Mac-App", id: 1463298887
mas "WiFi Explorer", id: 494803304
mas "WireGuard", id: 1451685025
mas "‎WhatsApp", id: 310633997
vscode "aaron-bond.better-comments"
vscode "achil.vscode-javascript-repl"
vscode "alefragnani.Bookmarks"
vscode "alefragnani.project-manager"
vscode "bierner.github-markdown-preview"
vscode "bierner.markdown-checkbox"
vscode "bierner.markdown-emoji"
vscode "bierner.markdown-footnotes"
vscode "bierner.markdown-mermaid"
vscode "bierner.markdown-preview-github-styles"
vscode "bierner.markdown-yaml-preamble"
vscode "bradlc.vscode-tailwindcss"
vscode "burkeholland.simple-react-snippets"
vscode "Catppuccin.catppuccin-vsc"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "Ciantic.keymapceditor-vsc"
vscode "cmstead.js-codeformer"
vscode "cmstead.jsrefactor"
vscode "codezombiech.gitignore"
vscode "cschlosser.doxdocgen"
vscode "Dart-Code.dart-code"
vscode "Dart-Code.flutter"
vscode "DavidAnson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "denoland.vscode-deno"
vscode "DiemasMichiels.emulate"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "eg2.vscode-npm-script"
vscode "enkia.tokyo-night"
vscode "esbenp.prettier-vscode"
vscode "felixjb.testify"
vscode "file-icons.file-icons"
vscode "firefox-devtools.vscode-firefox-debug"
vscode "formulahendry.code-runner"
vscode "fwcd.kotlin"
vscode "GitHub.codespaces"
vscode "GitHub.copilot"
vscode "GitHub.copilot-chat"
vscode "github.vscode-github-actions"
vscode "GitHub.vscode-pull-request-github"
vscode "golang.go"
vscode "GrapeCity.gc-excelviewer"
vscode "Gruntfuggly.todo-tree"
vscode "hediet.debug-visualizer"
vscode "humao.rest-client"
vscode "infeng.vscode-react-typescript"
vscode "jeff-hykin.better-cpp-syntax"
vscode "johnpapa.vscode-peacock"
vscode "josetr.cmake-language-support-vscode"
vscode "joshbolduc.commitlint"
vscode "kisstkondoros.vscode-gutter-preview"
vscode "me-dutour-mathieu.vscode-github-actions"
vscode "MeshIntelligentTechnologiesInc.pieces-vscode"
vscode "miguelsolorio.fluent-icons"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.powershell"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "ms-vscode.vscode-serial-monitor"
vscode "ms-vsliveshare.vsliveshare"
vscode "ms-vsliveshare.vsliveshare-audio"
vscode "ms-vsliveshare.vsliveshare-pack"
vscode "msjsdiag.vscode-react-native"
vscode "nick-lvov-dev.typescript-explicit-types"
vscode "nrwl.angular-console"
vscode "Orta.vscode-jest"
vscode "Orta.vscode-ts-markdown-to-playground"
vscode "Orta.vscode-twoslash-queries"
vscode "paulmolluzzo.convert-css-in-js"
vscode "PKief.material-icon-theme"
vscode "pmneo.tsimporter"
vscode "pnp.polacode"
vscode "PollywogGames.pico8-ls"
vscode "quicktype.quicktype"
vscode "rbbit.typescript-hero"
vscode "redhat.java"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "silvenon.mdx"
vscode "sswg.swift-lang"
vscode "stringham.move-ts"
vscode "tamasfe.even-better-toml"
vscode "tomoyukim.vscode-mermaid-editor"
vscode "twxs.cmake"
vscode "vadimcn.vscode-lldb"
vscode "VisualStudioExptTeam.intellicode-api-usage-examples"
vscode "VisualStudioExptTeam.vscodeintellicode"
vscode "vsciot-vscode.vscode-arduino"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "Vue.volar"
vscode "Wattenberger.footsteps"
vscode "wix.vscode-import-cost"
vscode "xyc.vscode-mdx-preview"
vscode "yzhang.markdown-all-in-one"
vscode "zh9528.file-size"
vscode "ziyasal.vscode-open-in-github"
